name: Create and Upload Release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create Release Folder
      run: mkdir -p releases
    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=$(date +'%Y.%m.%d_%H-%M-%S')" >> $GITHUB_OUTPUT
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'releases/release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "releases/release.zip"
        tag: ${{ steps.tag.outputs.release_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
